export const Amulet = [
"Any",
"Fire Ruby of Wealth",
"Frost Amulet of Luck",
"Choker",
"Hawk's Eye",
"Fire Pendant of Wealth",
"Chain",
"Cat's Eye",
"Torc",
"Tiger's Eye",
"Frost Pendant of Luck",
"Relic",
"Frost Opal of Luck",
"Life Amulet of Courage",
"Life Emerald of Courage",
"Life Pendant of Wealth",
"Fire Amulet of Wealth",
"Charm",
"Collar",
"Left Fang of Medusa",
"Celestial Claw",
"Talisman of Immutable Devotion",
"Holy Brooch of Tranquility",
"Galen's Observation",
"Asclepius's Resurrection",
"Song of Eternal Winter",
"Essence of Peace",
"Heart's Ember",
];