export const Antler = [
"Any",
"Jagged Antlers of Wealth",
"Magnificent Antlers of Courage",
"Bony Antlers",
"Heavy Antlers",
"Waxy Antlers of Luck",
"Velvet Covered Antlers of Courage",
"Heavy Antlers of Luck",
"Velvet Covered Antlers",
"Golden Antlers of Wealth",
"Broad Antlers of Luck",
"Magnificent Antlers",
"Sharp Antlers of Courage",
"Bony Antlers of Wealth",
"Sharp Antlers",
"Broad Antlers",
"Waxy Antlers",
"Jagged Antlers",
"Golden Antlers",
"Eternal Antlers of Sunlight",
"Ominous Antlers of Illusions",
"Enchanted Antlers of Sacred Dreams",
"Spectral Antlers of Infinite Trails",
"Vicious Antlers of Immortal Kings",
"Destiny's Antlers of the Oracle",
"Antlers of Timeless Ancestors",
"Bloodcursed Antlers of the Lost Worlds",
"Jeweled Antlers of the Prancing King",
];