export const Armor = [
"Any",
"Steel Breastplate of Luck",
"Polished Breastplate of Courage",
"Platemail Armor of Wealth",
"Battle Armor",
"Recruit Chestplate",
"Light Chestplate of Courage",
"Padded Chestplate",
"Steel Breastplate",
"Knight Chestplate of Luck",
"Light Chestplate",
"Heavy Armor",
"Padded Chestplate of Wealth",
"Copper Breasplate",
"Heavy Armor of Luck",
"Battle Armor of Courage",
"Polished Breastplate",
"Copper Breasplate of Wealth",
"Platemail Armor",
"Honor Bound Chestguard",
"Strength of Sorrow",
"Truth's Safeguard",
"Heart's Intent",
"Bloodfury's Guardian",
"Athena's Aid",
"Hephaestus's Gift",
"Armor of Achilles",
"Savior's Glory",
];