export const Bow = [
"Any",
"Long Bow",
"Recurve Bow",
"Apollo's Sun Forged Bow",
"Short Bow of Luck",
"Ranger Bow",
"Recruit Bow",
"Carved Bow of Wealth",
"Artemis's Wrath",
"Hunting Bow of Luck",
"Sun's Fang",
"War Bow of Courage",
"Heart Seeker",
"Orion's Ascendance",
"Long Bow of Wealth",
"Truthseeker, Bow of Righteousness",
"The Forest's Benevolence",
"Short Bow",
"Soul Ripper",
"Composite Bow",
"Carved Bow",
"Composite Bow of Wealth",
"Hunting Bow",
"Battle Bow",
"Recurve Bow of Courage",
"Ranger Bow of Courage",
"Knight Bow of Luck",
"Wind Piercer",
];