export const Cape = [
"Any",
"Knight Cape of Luck",
"Forest Cape of Wealth",
"Battle Cape",
"Crimson Cape of Luck",
"Defender Cape",
"Bloody Cape of Luck",
"Bloody Cape",
"Ironthread Cape",
"Defender Cape of Courage",
"Crimson Cape",
"Recruit Cape",
"Thick Cape",
"Snakeskin Cape of Wealth",
"Battle Cape of Courage",
"Thick Cape of Wealth",
"Forest Cape",
"Ironthread Cape of Courage",
"Snakeskin Cape",
"Minerva's Triumph",
"Heracles's Poison Stained Cape",
"Emerald Fortitude",
"Formidable Will",
"Solitude's Cape of Hatred",
"Wings of the Phoenix",
"Cape of the Emerald Champion",
"Spider Silk Cape of Arachne",
"Cape of Engulfing Flame",
];