export const Cloak = [
"Any",
"Jacket of Luck",
"Robes of the Haunted Forest",
"Flamesilk Robes of Precision",
"Hunting Cloak of Luck",
"Fleece Cowl",
"Ranger Cloak",
"Icy Capote of the Metis",
"Jacket of Wealth",
"Heart's Wrap",
"Dyed Pelt",
"Sunsfire",
"Recruit Cloak",
"Fur Cowl",
"Wrap",
"Enveloping Cloak of Wealth",
"Burnoose of Warm Dreams",
"Shawl",
"Pathfinder's Poncho of Wealth",
"Ranger Cloak of Courage",
"Shaded Shroud of Wealth",
"Stole",
"Jacket of Courage",
"Linen Drape",
"Knight Cloak of Luck",
"Bendis's Shroud of the Moon Hunt",
"Mantle of Ominous Illusions",
"Cloak of Whispering Night",
"Arcane Imbued Cloak of Wealth",
"Twilight Drape of Wealth",
"Dinner Cape",
"Scarf",
"Scholar's Cloak of Luck",
"Wind Proof Shroud of Courage",
"Misty Shroud of Courage",
"Ceremonial Cloak",
"Fancy Cloak of Luck",
"Wool Cowl",
"Gold Threaded Cape of Luck",
"Frostwoven Shroud of Courage",
"Midnight Wrap of Wealth",
"Dusty Drape",
"Apprentice Cloak",
"Frayed Cloak",
"Illuminating Cover of Thanateros",
"Heartbinder",
"Frostfire",
"Crowley's Shawl of Deconditioning",
"Shadow of Vengence",
"Silverglow",
"Death's Embrace",
"Cover of Unforgotten Truth",
"Zoroaster's Robe of Creation",
"Cloak of Whispering NIght",
];