export const Earring = [
"Any",
"Dainty Earring of Wealth",
"Recruit Earring of Luck",
"Recruit Earring",
"Bold Earring of Wealth",
"Dainty Earring",
"Polished Earring",
"Silver Earring of Wealth",
"Battle Earring of Courage",
"Looped Earring of Luck",
"Battle Earring",
"Bold Earring",
"Polished Earring of Luck",
"Sparkling Earring of Courage",
"Looped Earring",
"Sparkling Earring",
"Silver Earring",
"Salty Earring of Courage",
"Salty Earring",
"Death's Insurance",
"Thalassa's Bite",
"Earring of the Stalwart Captain",
"Golden Loop of Perception",
"Wind's Sting",
"Ruthlessness",
];