export const Eye_Patch = [
"Any",
"Salty Eye Patch of Courage",
"Battle Eye Patch of Courage",
"Leather Eye Patch of Wealth",
"Hardened Eye Patch of Wealth",
"Recruit Eye Patch of Luck",
"Hardened Eye Patch",
"Ink Stained Eye Patch",
"Recruit Eye Patch",
"Other Eye Patch",
"Tobacco Tinged Eye Patch of Wealth",
"Salty Eye Patch",
"Comfortable Eye Patch",
"Comfortable Eye Patch of Courage",
"Other Eye Patch of Luck",
"Ink Stained Eye Patch of Luck",
"Tobacco Tinged Eye Patch",
"The First Eye Patch of Jalhami",
"Unbreakable Diamond Eye Plate",
"Bonny's Mistrust",
"Suppressed Gaze of the Executioner",
"Rum Soaked Eye Covering",
"Leather Eye Patch",
"Battle Eye Patch",
"Eye Cover of Strategic Insight",
"Poseidon's Protection",
];