export const Hat = [
"Any",
"Alluring Hat of Luck",
"Wide Brimmed Hat",
"Traveler's Hat",
"The Immaculate Touch of Hygeia",
"Purifier's Fervor",
"Melampus's Soothing Influence",
"Nature's Revitalizing Essence",
"Conjurer's Hat",
"Durable Hat",
"Enchanter's Hat of Courage",
"Battle Hat",
"Apprentice Hat",
"Durable Hat of Wealth",
"Traveler's Hat of Luck",
"Floppy Hat of Wealth",
"Conjurer's Hat of Wealth",
"Wide Brimmed Hat of Courage",
"Enchanter's Hat",
"Alluring Hat",
"Battle Hat of Courage",
"Floppy Hat",
"Apprentice Hat of Luck",
"The Reprieve of Agathos",
"Berry Picker's Cap of Courage",
"Woodland Bycocket of Wealth",
"Lucky Fishing Hat of Wealth",
"Alpine Tyrolean Hat of Luck",
"Straw Fedora",
"Field Hat",
"Flat Brimmed Hat",
"Emerald Court Hat of Wealth",
"Cloth Hat",
"Knit Hat",
"Skull Cap",
"Violet Explorers Hat of Courage",
"Silk Hat",
"Jungle Hat",
"Denim Ranger Hat of Luck",
"Dinner Hat",
"Lavender Scented Poet Hat of Courage",
"Caubeen of Harmonic Whispers",
"Silenus' Cap of Rhythm",
"Orpheus's Beret of Virtuosity",
"Felted Cavalier Hat of Restoration",
"Unholy Conjurer's Hat",
"Unholy Battle Hat of Courage",
"Unholy Apprentice Hat",
"Unholy Traveler's Hat of Luck",
"Unholy Enchanter's Hat",
"Unholy Apprentice Hat of Luck",
"Unholy Traveler's Hat",
"Unholy Floppy Hat of Wealth",
"Unholy Battle Hat",
"Unholy Durable Hat of Wealth",
"Unholy Floppy Hat",
"Unholy Wide Brimmed Hat of Courage",
"Unholy Enchanter's Hat of Courage",
"Unholy Durable Hat",
"Unholy Alluring Hat",
"Unholy Alluring Hat of Luck",
"Tormented Mind",
"Blind Vengeance",
"Miseria",
"Hood of Hungering Doom",
"Unholy Wide Brimmed Hat",
"Unholy Conjurer's Hat of Wealth",
"Gaze of the Corruptor",
"Moros's Fate",
"Cover of Crippling Darkness",
"Fancy Beret of Luck",
"Spider Silk Woven Bonnet",
"Landini's Chaperon of Cadence",
"Pillar of Midnight",
"Final Absolution",
"Light's Resolution",
"Faith of the Mender",
"The Necronomicon",
"Corrupted Tome of Light",
"Dictionnaire Infernal",
"Soulhunter",
"Dread of Deimos",
"Hypnotizing Conductor's Cap",
];