export const Helm = [
"Any",
"Battle Helm",
"Heavy Helm of Luck",
"Light Helm",
"Copper Helm of Wealth",
"Light Helm of Courage",
"Platemail Helm of Wealth",
"Terror of Phobos",
"Polished Helm",
"Polished Helm of Courage",
"Steel Helm",
"Copper Helm",
"Padded Helm of Wealth",
"Recruit Helm",
"Platemail Helm",
"Steel Helm of Luck",
"Heavy Helm",
"Padded Helm",
"Recruit Helm of Luck",
"Battle Helm of Courage",
"Helm of Righteous Might",
"Greathelm of Empowered Fate",
"Androktasia",
"Faceplate of the Subjugator",
"Crown of Haunted Kings",
"Achilles's Visage",
"Wings of Hope",
"Gaze of Eternal Sleep",
];