export const Lute = [
"Any",
"Setar",
"Blood Kissed Aarbajo of Wealth",
"Heavy Brass Sursingar of Luck",
"Citole",
"Pandura",
"Ruby Studded Phin of Wealth",
"Oud",
"Gold Speckled Gambus of Luck",
"Cura",
"Pipa",
"Crystal Lined Komuz of Courage",
"Liuqin",
"Wine Stained Gittern of Wealth",
"Russet Dutar of Luck",
"Biwa",
"Snow Covered Bandola of Courage",
"Charred Mandolin of Courage",
"Venus's Lute of Serenading",
"Shiva Blessed Rudra Veena",
"Ascetic's Dotara of Mysticism",
"Experimental Cythara of Spellbinding",
"Barbat",
"Ancient Beeswax Kutiyapi",
"Life Keeper's Turtle Shell Gunibri",
"Hermes's Laouto of Guidance",
"Magma Coated Sarod",
];