export const Quiver = [
"Any",
"Eros's Desire",
"Battle Quiver",
"Hunting Quiver of Luck",
"Mossy Quiver of Wealth",
"Hardened Quiver",
"Thornscreamer",
"Fangs of Corruption",
"Small Quiver",
"Razorspine",
"Ranger Quiver of Courage",
"War Quiver of Courage",
"Composite Quiver of Wealth",
"Leather Quiver",
"Hardened Quiver of Luck",
"Large Quiver of Wealth",
"Leather Quiver of Wealth",
"Knight Quiver of Luck",
"Recruit Quiver",
"Liar's Remedy",
"Heart Piercer",
"Philoctetes's Cruelty",
"Hunting Quiver",
"Composite Quiver",
"Mossy Quiver",
"Nessus's Revenge",
"Fleshripper",
"Ranger Quiver",
];