export const Staff = [
"Any",
"Purified Staff of Luck",
"Oak Staff",
"Hazel Staff",
"Glory of Hera",
"Light's Purge",
"Demeter's Harvest",
"Yew Staff",
"Nature's Requiem",
"Purified Staff of Courage",
"Conjurer's Staff of Courage",
"Conjurer's Staff of Wealth",
"Conjurer's Staff of Luck",
"Benediction",
"Purified Staff of Wealth",
"Perfectly Balanced Staff of Courage",
"Apprentice Staff",
"Battle Staff",
"Ash Staff",
"Perfectly Balanced Staff of Wealth",
"Lunar Staff",
"Maple Staff",
"Twisting Transgression",
"Perfectly Balanced Staff of Luck",
"Elder Staff",
];