export const Sword = [
"Any",
"Fine Cutlass of Wealth",
"Salty Cutlass of Courage",
"Steel Scimitar of Courage",
"Very Sharp Cutlass of Luck",
"Recruit Scimitar",
"Knight Scimitar of Luck",
"Durable Scimitar",
"Fine Cutlass",
"Durable Scimitar of Wealth",
"Salty Cutlass",
"Flexible Sabre",
"Battle Sabre",
"Iron Sabre of Wealth",
"Flexible Sabre of Luck",
"Very Sharp Cutlass",
"Battle Sabre of Courage",
"Steel Scimitar",
"The Victual",
"Blade of the Banished",
"Blackbeard's Renown",
"Battle Sword",
"Iron Arming Sword of Wealth",
"Steel Gladius of Luck",
"Bronze Short Sword",
"Recruit Sword",
"Heavy Gladius",
"Hardened Short Sword",
"Tempered Short Sword of Luck",
"Knight Sword of Luck",
"Tempered Short Sword",
"Damascus Sword",
"Steel Gladius",
"Battle Sword of Courage",
"Heavy Gladius of Wealth",
"Hardened Short Sword of Wealth",
"Bronze Short Sword of Courage",
"Iron Arming Sword",
"Damascus Sword of Courage",
"Mourneblade",
"Misery's End",
"Onslaught",
"Harpe",
"Colada",
"Oathkeeper",
"Ares's Bloodlust",
"Evil's Kiss",
"Shieldbreaker",
"Iron Sabre",
"Stormcutter",
"Bloodthirster",
"Black Bart",
];