export const Tome = [
"Any",
"Holy Spellbook",
"Holy Manual",
"Holy Spellbook of Courage",
"Spellbinder's Book of Hope",
"Hand of Glory",
"Codex of Healing Light",
"The Sworn Book of Honorius",
"Holy Manual of Wealth",
"Holy Book of Luck",
"Holy Guide of Wealth",
"Holy Tome of Courage",
"Holy Volume",
"Holy Text",
"Holy Volume of Luck",
"Secrets of the Divine",
"Holy Ledger",
"Holy Index",
"Holy Grimoire",
"Holy Tome",
"Holy Text of Wealth",
"Holy Guide",
"Holy Ledger of Luck",
"Holy Grimoire of Courage",
"Purified Tome of Darkness",
"Unholy Ledger of Luck",
"Unholy Therimoire",
"Unholy Tome",
"Unholy Guide of Wealth",
"Unholy Tome of Courage",
"Unholy Book of Luck",
"Unholy Text",
"Unholy Manual of Wealth",
"Unholy Text of Wealth",
"Unholy Volume of Luck",
"Unholy Manual",
"Unholy Spellbook",
"Unholy Spellbook of Courage",
"Unholy Guide",
"Unholy Volume",
"Unholy Ledger",
"Unholy Index",
"Book of the Dead",
"Corrupted Tome of Light",
"Tome of Dominating Fate",
"Manifest of Suffering",
"Unholy Therimoire of Courage",
"Death's Whispers",
"Dictionnaire Infernal",
"Forbidden Truth",
"The Necronomicon",
"Record of Guiding Light",
"Life Binder's Invocation",
"The Magus",
"Key of Solomon",
];