export const Wand = [
"Any",
"Blasting Rod of Earthern Courage",
"Lunar Wand",
"Moon Blessed Wand of Wealth",
"Hazel Wand",
"Elder Wand",
"Maple Wand",
"Oak Wand",
"Blasting Rod of Firey Luck",
"Battle Wand",
"Ash Wand",
"Yew Wand",
"Apprentice Wand",
"Unbreakable Wand of Courage",
"Incorruptible Wand of Luck",
"Blasting Rod of Watery Wealth",
"Sun Scorched Wand of Courage",
"Bone Chilling Wand of Luck",
"Unyielding Wand of Wealth",
"Rod of Twisting Doom",
"Golden Dawn",
"Dominating Will",
"Nature's Deliverance",
"Astral Light",
"Demonspine",
"Death's Sting",
"Eliphas's Dialectic",
"Hermes's Caduceus",
"Hermes’s Caduceus",
];